---
- name: Gather RPM package version
  ansible.builtin.command: "rpm -qp --queryformat '%{VERSION}' /tmp/{{ sentinelone_filename | basename }}"
  register: sentinelone_rpm_version
  changed_when: false

- name: Set nodigest flag, if required
  ansible.builtin.set_fact:
    sentinelone_digest: '--nodigest'
  when:
    - "sentinelone_rpm_version.stdout is version('23.3.2.12', '<')"
